#%RAML 1.0 Library

types:
  # Exported AccountTypes
  Account:
    type: !include ./Account.cdm.json
  Contact:
    type: !include ./Contact.cdm.json
  Lead:
    type: !include ./Lead.cdm.json
  AccountLeads:
    type: !include ./AccountLeads.cdm.json
  ContactLeads:
    type: !include ./ContactLeads.cdm.json
  LeadAddress: 
    type: !include ./LeadAddress.cdm.json
