#%RAML 1.0 Library

types:
  # Exported AccountTypes
  Account:
    type: !include ./Account.cdm.json
  Contact:
    type: !include ./Contact.cdm.json
  Lead:
    type: !include ./Lead.cdm.json
  AccountPartner:
    type: AccountTypes.AccountPartner
    example: !include ./examples/AccountPartnerExample.json
  Lead:
    type: AccountTypes.Lead
    example: !include ./examples/LeadExample.json

  Customer: !include /exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/CustomerSchema.json
  Lead: !include /exchange_modules/org.mule.examples/accelerator-cim-library/1.1.1/jsonSchemas/LeadSchema.json